////----------------------------------------//
///SuperDepth3D Sentinel Profile Automation///
//----------------------------------------////
// Sentinel v1.0.0
//---------------------------------------SENTINEL----------------------------------------//
// Overwatch covers the position and Recon scouts ahead. Sentinel holds the post and     //
// stands watch over the Generic Depth Mod Add-on for as long as the game runs.          //
// The name comes from this.                                                             //
// https://en.wikipedia.org/wiki/Sentry                                                  //
// Since this File hands the Add-on the settings a game wants before it picks a buffer.  //
//---------------------------------------------------------------------------------------//
// Do not edit this file. It is generated, and the next Depth3D shader update replaces   //
// it, so anything changed here is lost. To change a game use the Add-on's own options;  //
// what you save there is kept in ReShade.ini and wins over every default below.         //
//----------------------------------------LICENSE----------------------------------------//
// ===================================================================================== //
// Sentinel is licenses under: Copyright (C) Depth3D - All Rights Reserved               //
//                                                                                       //
// Unauthorized copying of this file, via any medium is strictly prohibited              //
// Proprietary and confidential.                                                         //
//                                                                                       //
// You are allowed to obviously download this and use this for your personal use.        //
// Just don't redistribute this file unless I authorize it.                              //
//                                                                                       //
// Written by Jose Negrete <UntouchableBlueSky@gmail.com>, September 2026                //
// ===================================================================================== //
//-----------------------------------------NOTE------------------------------------------//
// A guide, for anyone who wants a game added or an existing profile corrected.          //
//                                                                                       //
// 1. Set the game up the way it should be, using the Add-on's own options.              //
//                                                                                       //
// 2. Open the game's ReShade.ini and find the [DEPTH] section. Everything you           //
//    changed is already sitting there in the exact shape this file wants, so you        //
//    can copy those lines straight across. Drop the ones still at their default.        //
//                                                                                       //
// 3. Find your game's id. It is in ReShade.log, at the end of the first line:           //
//    Initializing crosire's ReShade ... into '...\YourGame.exe' (0x1234ABCD) ...        //
//    That number in brackets is the section name to use.                                //
//                                                                                       //
// 4. Fill in the template just below and send it to me on Discord.                      //
//    https://discord.gg/W2f7YhX                                                         //
//--------------------------------------Data Start---------------------------------------//
// Section name is the ReShade application id, the same number Overwatch.fxh matches on. //

//---------------------------------------SETTINGS----------------------------------------//
// Every option the Add-on takes. Each one shows the name you see in the Add-on, then    //
// the values it accepts. Use this as the reference while filling in the TEMPLATE below. //
//---------------------------------------------------------------------------------------//

// [0x1234ABCD]                              // your game's id, from ReShade.log (see NOTE above)
// Game=Your Game Name
//
// Buffer selection:
//   Start here. These decide WHICH depth buffer is used. Format and aspect ratio alone fix
//   most games; only reach past them if the wrong buffer is still being picked.
//
// FilterFormat=                            // Filter by depth buffer format
//                                          //   0 All | 1 D16 | 2 D16S8 | 3 D24X8 | 4 D24S8 | 5 D32 | 6 D32S8 | 7 INTZ
// DrawStatsHeuristic=                      // Draw stats heuristic
//                                          //   0 Default | 1 Higher vertices | 2 Higher draw calls | 3 Lower vertices | 4 Lower draw calls
// UseAspectRatioHeuristics=                // Aspect ratio heuristic
//                                          //   0 None | 1 Similar aspect ratio | 2 Multiples of resolution (for DLSS or resolution scaling) | 3 Match resolution exactly | 4 Match custom width and height exactly
// FilterResolutionWidth=                   // Filter by width and height
//                                          //   a number - only with Aspect ratio heuristic 4
// FilterResolutionHeight=                  // Filter by width and height
//                                          //   a number - only with Aspect ratio heuristic 4
// TargetMSAA=                              // Targets the multisampled buffer if it is available
//                                          //   0 off | 1 on - only for games with a multisampled depth buffer
// DoNotSkipUpdate=                         // Don't skip update when there is little activity
//                                          //   0 off | 1 on - for Xash3D style games that flicker when idle
// IgnoreUnusableBufferInList=              // Ignore buffers that are unusable in the list
//                                          //   0 off | 1 on - hides idle and clear-only buffers from the list
//
// Selection priorities:
//   Tie breakers for when several buffers look alike. Set ONE and test. Stacking them
//   usually makes the choice less stable, not more.
//
// DepthBufferForcedHeuristics=             // Select the primary prioritized attribute
//                                          //   0 Auto | 1 Vertices | 2 Draw calls
// PrioritizeIndirectDrawcallsHigh=         // Prioritize high indirect calls
//                                          //   0 off | 1 on
// IgnoreIndirectDrawcallsGreater=          // Limit prioritize indirects
//                                          //   0 off | 1 on - caps the option above, only with it on
// PrioritizeIndirectDrawcallsLow=          // Prioritize low indirect calls
//                                          //   0 off | 1 on
// AvoidHighVertices=                       // Prioritize lower vertices counts
//                                          //   0 off | 1 on
// AvoidHighDrawcalls=                      // Prioritize lower drawcalls counts
//                                          //   0 off | 1 on
// PreferNonReversedBuffers=                // Prioritize Safe buffers
//                                          //   0 off | 1 on
//
// Skip rules:
//   Rules a buffer out by its draw stats. Use when the wrong buffer wins for a few frames,
//   typically in menus or cutscenes. Each inequality line needs its matching value line.
//
// FilterAvoidenceValues=                   // Select the attribute and enter values to avoid
//                                          //   0 Off | 1 Set Vertice Value to avoid | 2 Set Drawcall Value to avoid | 3 Set Both Vertice & Drawcall Value to avoid
// FilterVerticesValue_A=                   // Enter avoided vertice values
//                                          //   a number - with the option above set to 1 or 3, also _B _C _D
// FilterDrawcallsValue_A=                  // Enter avoided drawcall values
//                                          //   a number - with the option above set to 2 or 3, also _B _C _D
// InequalityVerticesValue=                 // Select inequality for Vertices
//                                          //   0 Off | 1 Vertices greater than value | 2 Vertices less than value
// FilterInequalityVerticesValue=           // Enter vertice value
//                                          //   a number - the value the rule above compares against
// InequalityDrawcallValue=                 // Select inequality for Drawcalls
//                                          //   0 Off | 1 Drawcalls greater than value | 2 Drawcalls less than value
// FilterInequalityDrawcallValue=           // Enter drawcall value
//                                          //   a number - the value the rule above compares against
// InequalityIndirectDrawcallValue=         // Select inequality for Indirect Drawcalls
//                                          //   0 Off | 1 Indirect Drawcalls greater than value | 2 Indirect Drawcalls less than value
// FilterInequalityValuesIndirectDrawcall=  // Enter indirect drawcall value
//                                          //   a number - the value the rule above compares against
// PrioritizeIndirectDrawcallsZero=         // Set indirect drawcalls if zero
//                                          //   0 off | 1 on
// IgnoreIndirectDrawcallsZero=             // Skip indirect drawcalls if zero
//                                          //   0 off | 1 on
// IgnoreDrawcallsZero=                     // Skip drawcalls if zero
//                                          //   0 off | 1 on
// IgnoreVerticesZero=                      // Skip vertices if zero
//                                          //   0 off | 1 on
//
// Depth copies:
//   For games that clear or reuse the depth buffer before the shader reads it. The symptom
//   is depth that flickers, or freezes while the camera keeps moving. Try the first copy
//   option on its own before the during-frame one; both cost performance.
//
// AvoidSelectedDepthBufferClear=           // Select Max disallowed clear buffers
//                                          //   0 Off | 1 Greater Than One | 2 Greater Than Two | 3 Greater Than Three | 4 Greater Than Four | 5 Greater Than Five
// DepthBufferClearIndex=                   // Select Minimal allowed clear buffer
//                                          //   0 Off | 1 Less Than One | 2 Less Than Two | 3 Less Than Three | 4 Less Than Four | 5 Less Than Five
// AvoidHighVerticesOnClear=                // Select the level to avoid high vertices on clear
//                                          //   0 Off | 1 Max | 2 Mid | 3 Min | 4 Assertive | 5 Reserved
// DisableRestrictions=                     // Disable restrictions that allow selection of zero buffers
//                                          //   0 off | 1 on
// DepthCopyBeforeClears=                   // Copy depth buffer before clear operations
//                                          //   0 off | 1 on - 2 also turns on 'Copy depth buffer during frame'
// DisableDrawCallRestrictionOnClear=       // Disable draw call restriction during frame
//                                          //   0 off | 1 on - only with DepthCopyBeforeClears 2
// SkipFullscreenDraw=                      // Skip clear with fullscreen draws
//                                          //   0 off | 1 on - only with DepthCopyBeforeClears 2
//
// Pooled buffers:
//   For engines that rotate the scene depth through several buffers every frame, common in
//   DX12. The symptom is depth that alternates between right and wrong, or stops updating
//   while the camera moves. Turn all three on together; they are built to work as a set.
//
// MergePooledBuffers=                      // Merge pooled buffer copies
//                                          //   0 off | 1 on
// CopyOnCommandListClose=                  // Copy when the scene command list is closed
//                                          //   0 off | 1 on - DX12 and Vulkan only
// PooledCopySharing=                       // Copy from pooled buffer copies
//                                          //   0 off | 1 on - needs MergePooledBuffers
//
// Depth Buffer Fit:
//   On by default and normally left alone. It lands the depth on the image pixel for pixel
//   when the game renders at one size and displays at another, as upscalers do. Only set
//   the second line if cutscenes are misaligned while normal play is fine.
//
// DepthAutoFit=                            // Take over depth fit (exact)
//                                          //   0 off | 1 on - on by default, turn off only if it hurts
// DepthAutoFitMaxViewport=                 // Measure against full render region (upscaler cutscenes)
//                                          //   0 off | 1 on
//
// Generic Weapon Depth:
//   First person games only, and only when the weapon or hands need depth of their own:
//   they look flat, sink into the world, or hurt to look at near the screen edge. Start
//   with detection on Auto and leave the rest out. The manual lines are for games where
//   Auto pins the wrong clear; you read the number off the clear list in the overlay.
//
// WDepthDetectionMode=                     // Weapon hand (WDEPTH) detection
//                                          //   0 Off | 1 Auto (live capture)
// WDepthWeaponLarger=                      // Weapon has MORE vertices than the world (flip for strange games)
//                                          //   0 off | 1 on - only if the weapon has MORE vertices than the world
// WDepthManualOverride=                    // Enable manual weapon clear override
//                                          //   0 off | 1 on - only if Auto pins the wrong clear
// WDepthClearIndex=                        // WEAPON boxes in the clear list
//                                          //   a number - the clear to pin, with the override on
// WDepthClearPosition=                     // WEAPON clear position
//                                          //   0 First | 1 Second | 2 Third | 3 Fourth | 4 Last - with the override on
//
// Game specific workarounds:
//   Set only the one that names your game, and only together with the other options its
//   guide lists under Extra Information in the Add-on. They do nothing in any other game,
//   and most stay hidden in the overlay until those other options are set.
//
// TLoUWorkaround=                          // The Last of Us: Part One workaround
//                                          //   0 off | 1 on - The Last of Us: Part One
// KHBbSWorkaround=                         // KHBbSWorkaround
//                                          //   0 Off | 1 Clears | 2 Indirects - Kingdom Hearts: Birth by Sleep
// KHWorkaround=                            // Kingdom Hearts: Dream Drop Distance workaround
//                                          //   0 off | 1 on - Kingdom Hearts: Dream Drop Distance
// BanisherWorkaround=                      // Banishers crash workaround
//                                          //   0 off | 1 on - Banishers: Ghosts of New Eden
// ThaumaturgeWorkaround=                   // Thaumaturge crash workaround
//                                          //   0 off | 1 on - The Thaumaturge
// KTWorkaround=                            // Killing Time workaround
//                                          //   0 off | 1 on - Killing Time: Resurrected

//-------------------------------------Settings End--------------------------------------//

//---------------------------------------TEMPLATE----------------------------------------//
// Copy this, fill it in for your game, and send it to me on Discord.                    //
// Delete every line you are not setting. Only the lines you keep are applied, and the   //
// Add-on falls back to its own default for the rest.                                    //
//---------------------------------------------------------------------------------------//

[0x0000000]
Game=GAME NAME
FilterFormat=6
UseAspectRatioHeuristics=2
DisableRestrictions=1
DepthCopyBeforeClears=1

//-------------------------------------Template End--------------------------------------//

//Profiles:

[0xDCFDCBA7]
Game=Assassin's Creed Shadows (id 1 of 2)
FilterFormat=6
UseAspectRatioHeuristics=2
DisableRestrictions=1
DepthCopyBeforeClears=1

[0x64AF115E]
Game=Assassin's Creed Shadows (id 2 of 2)
FilterFormat=6
UseAspectRatioHeuristics=2
DisableRestrictions=1
DepthCopyBeforeClears=1

[0x120C9132]
Game=The Last of Us Part II
DepthCopyBeforeClears=1
FilterFormat=6
PrioritizeIndirectDrawcallsHigh=1

[0x49D2CF5E]
Game=Lies of P
UseAspectRatioHeuristics=2
IgnoreIndirectDrawcallsZero=1
FilterFormat=6

[0x4B794AD5]
Game=KIBORG
DisableRestrictions=1

[0xC9C4ACAB]
Game=Avowed (id 1 of 2)
FilterFormat=6
DepthBufferForcedHeuristics=1
UseAspectRatioHeuristics=2
InequalityDrawcallValue=2
FilterInequalityDrawcallValue=8
AvoidHighDrawcalls=1
DisableRestrictions=1
DepthCopyBeforeClears=1

[0xC1935FB5]
Game=Avowed (id 2 of 2)
FilterFormat=6
DepthBufferForcedHeuristics=1
UseAspectRatioHeuristics=2
InequalityDrawcallValue=2
FilterInequalityDrawcallValue=8
AvoidHighDrawcalls=1
DisableRestrictions=1
DepthCopyBeforeClears=1

[0x808ABB25]
Game=BioShock Infinite //Steam //Epic (id 1 of 2)
AvoidHighVerticesOnClear=2

[0x87871191]
Game=BioShock Infinite //Steam //Epic (id 2 of 2)
AvoidHighVerticesOnClear=2

[0xD93B8576]
Game=Black Myth: Wukong
DepthBufferForcedHeuristics=1
InequalityVerticesValue=2
FilterInequalityVerticesValue=10
DisableRestrictions=1

[0x51C8FDAA]
Game=Assassin's Creed Valhalla
DisableRestrictions=1

[0x8F017168]
Game=System Shock 2: 25th Anniversary Remaster
DepthCopyBeforeClears=1
FilterFormat=5

[0x71170B42]
Game=Blood: Fresh Supply
DepthBufferForcedHeuristics=2
AvoidHighDrawcalls=1
DisableRestrictions=1

[0x2E9781B5]
Game=QRSL
DepthCopyBeforeClears=2

[0x64317982]
Game=Baldur's Gate 3 (id 1 of 2)
DepthCopyBeforeClears=2

[0x1332A12F]
Game=Baldur's Gate 3 (id 2 of 2)
DepthCopyBeforeClears=2

[0x301B8589]
Game=Wuchang: Fallen Feathers
DepthBufferForcedHeuristics=1
UseAspectRatioHeuristics=2
IgnoreUnusableBufferInList=1
DisableRestrictions=1

[0xDC9787C6]
Game=Metal Gear Solid Delta: Snake Eater
FilterFormat=6
DepthBufferForcedHeuristics=1
UseAspectRatioHeuristics=2
DisableRestrictions=1
DepthCopyBeforeClears=1

[0xC06FF3FD]
Game=Borderlands 4
FilterFormat=6
DrawStatsHeuristic=4
UseAspectRatioHeuristics=2
InequalityVerticesValue=2
FilterInequalityVerticesValue=3
InequalityDrawcallValue=2
FilterInequalityDrawcallValue=35
IgnoreIndirectDrawcallsZero=1
IgnoreVerticesZero=1

[0x6DE081CF]
Game=Alan Wake 2
FilterFormat=5
UseAspectRatioHeuristics=1
DepthCopyBeforeClears=2

[0xC34702F]
Game=Megabonk
DepthCopyBeforeClears=1

[0xB04473F8]
Game=Eclipsium
UseAspectRatioHeuristics=2

[0x35FC0B4A]
Game=Silent Hill f
UseAspectRatioHeuristics=2

[0x3BDD00D4]
Game=Little Nightmares 3
UseAspectRatioHeuristics=2

[0xEA37502D]
Game=Aliens: Dark Descent
UseAspectRatioHeuristics=2

[0x5AA16DA7]
Game=South of Midnight
UseAspectRatioHeuristics=2

[0x54D4EAFA]
Game=Sekiro: Shadows Die Twice
FilterFormat=6

[0x710BB66B]
Game=Sniper Ghost Warrior Contracts 2
FilterFormat=6

[0xB78730C7]
Game=Hogwarts Legacy
FilterFormat=6

[0x7F3DE7B8]
Game=Painkiller 2025
UseAspectRatioHeuristics=2

[0x85F76405]
Game=Tormented Souls 2
UseAspectRatioHeuristics=2

[0x847D490D]
Game=Easy Delivery Co.
UseAspectRatioHeuristics=4

[0x74C54033]
Game=Diablo III
DepthCopyBeforeClears=1

[0x306F050D]
Game=Metal Garden
FilterFormat=6
DepthBufferForcedHeuristics=1
UseAspectRatioHeuristics=2
AvoidHighVertices=1

[0xA93E2110]
Game=Party Animals
DepthCopyBeforeClears=2

[0xB3729F40]
Game=Rocket League Steam
DepthCopyBeforeClears=1

[0x6C93390A]
Game=Lords of the Fallen 2023
FilterFormat=6
UseAspectRatioHeuristics=2
InequalityVerticesValue=2
FilterInequalityVerticesValue=6

[0xCBE94135]
Game=Anno: Mutationem
FilterFormat=6
UseAspectRatioHeuristics=2
DepthCopyBeforeClears=1

[0xD58F450]
Game=REANIMAL
FilterFormat=6
UseAspectRatioHeuristics=2
PrioritizeIndirectDrawcallsHigh=1
IgnoreIndirectDrawcallsZero=1

[0xD14A39CF]
Game=Crimson Desert
FilterFormat=6
UseAspectRatioHeuristics=2
PrioritizeIndirectDrawcallsLow=1
DisableRestrictions=1

[0x45C250C6]
Game=Dying Light 2 | Dying Light: The Beast (id 1 of 2)
UseAspectRatioHeuristics=2

[0x78822EB7]
Game=Dying Light 2 | Dying Light: The Beast (id 2 of 2)
UseAspectRatioHeuristics=2

[0x2D950D30]
Game=Fallout 4
UseAspectRatioHeuristics=2
DepthCopyBeforeClears=1

[0xB53B8500]
Game=DEATH STRANDING
UseAspectRatioHeuristics=2

[0xF97F5B96]
Game=The First Berserker: Khazan
UseAspectRatioHeuristics=2
FilterFormat=6
DepthCopyBeforeClears=2

[0xB6433F0D]
Game=John Carpenter's Toxic Commando
UseAspectRatioHeuristics=2

[0xD804BA96]
Game=Myst
FilterFormat=6
UseAspectRatioHeuristics=2
DoNotSkipUpdate=1
IgnoreUnusableBufferInList=1
DisableRestrictions=1
DepthCopyBeforeClears=1

[0x5D5EB177]
Game=Idol of Ash
UseAspectRatioHeuristics=2
FilterFormat=6

[0x621202BC]
Game=Vanquish DXVK
UseAspectRatioHeuristics=0

[0x22A11E54]
Game=Senua's Saga: Hellblade II - Windows Store & Steam (id 1 of 2)
FilterFormat=6
UseAspectRatioHeuristics=2
IgnoreIndirectDrawcallsZero=1
IgnoreUnusableBufferInList=1

[0x2AEB2784]
Game=Senua's Saga: Hellblade II - Windows Store & Steam (id 2 of 2)
FilterFormat=6
UseAspectRatioHeuristics=2
IgnoreIndirectDrawcallsZero=1
IgnoreUnusableBufferInList=1

[0x6DCAE83C]
Game=SnowRunner
UseAspectRatioHeuristics=1
DepthCopyBeforeClears=1

[0xAE8467CE]
Game=Ziggurat 2
FilterFormat=6
UseAspectRatioHeuristics=2
DepthCopyBeforeClears=1
WDepthDetectionMode=1

[0x7CB26776]
Game=Assassin's Creed Black Flag Resync
FilterFormat=6
UseAspectRatioHeuristics=0
DepthCopyBeforeClears=2

[0x3C7D25D8]
Game=Halo Campaign Evolved
UseAspectRatioHeuristics=2

[0x469CF719]
Game=Gears of War 2 Hollow
DepthCopyBeforeClears=1

[0x1CDCCDF5]
Game=Dawn Walker
DepthAutoFit=1
UseAspectRatioHeuristics=2

[0xD3CBA2BF]
Game=Moss Collection
DepthAutoFit=1
DepthBufferForcedHeuristics=2
UseAspectRatioHeuristics=2

[0xB663C9AE]
Game=Gears of War: Reloaded
DepthBufferForcedHeuristics=2
AvoidHighDrawcalls=1

[0x91C1C0C5]
Game=Dragon's Dogma 2
FilterFormat=6
UseAspectRatioHeuristics=2
PrioritizeIndirectDrawcallsLow=1
PreferNonReversedBuffers=1

[0x91555B0]
Game=007 First Light
FilterFormat=6
UseAspectRatioHeuristics=2
MergePooledBuffers=1
CopyOnCommandListClose=1
PooledCopySharing=1

[0x2CD728EE]
Game=Killing Time: Resurrected
KTWorkaround=1

[0x8CD69EAE]
Game=Kingdom Hearts: Birth by Sleep
DepthCopyBeforeClears=2
DisableRestrictions=1
AvoidHighVerticesOnClear=4
DepthBufferClearIndex=1
KHBbSWorkaround=2

[0x3CE12580]
Game=Kingdom Hearts: Dream Drop Distance
DepthCopyBeforeClears=2
DisableRestrictions=1
DisableDrawCallRestrictionOnClear=1
AvoidSelectedDepthBufferClear=1
KHWorkaround=1

[0x9EC5A0DB]
Game=The Thaumaturge
DepthCopyBeforeClears=2
DisableRestrictions=1
DisableDrawCallRestrictionOnClear=1
AvoidHighVertices=1
AvoidHighDrawcalls=1
ThaumaturgeWorkaround=1

[0xEE23A44]
Game=Banishers: Ghosts of New Eden
PrioritizeIndirectDrawcallsLow=1
DepthCopyBeforeClears=1
BanisherWorkaround=1

[0xB097DD6F]
Game=The Last of Us Part I
IgnoreUnusableBufferInList=1
DepthCopyBeforeClears=2
DisableDrawCallRestrictionOnClear=1
SkipFullscreenDraw=1
TLoUWorkaround=1

[0x7D8C8793]
Game=TERA
CopyOnCommandListClose=1

[0x76D21E12]
Game=Silent Hill Townfall
UseAspectRatioHeuristics=2
MergePooledBuffers=1
CopyOnCommandListClose=1
PooledCopySharing=1
DepthAutoFit=1
